### ISSUE TITLE
flask.cli.NoAppException : ImportError: No module named flask_minify

### ISSUE THREAD

**Issue by tnniras** [app-generator/flask-adminlte#10]
Hello Team,
I'm getting an error when trying to open the webpage in the 'development' environment. 

'''
flask.cli.NoAppException
NoAppException: While importing "run", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/root/MechanicWala/run.py", line 8, in <module>
    from   flask_minify  import Minify
ImportError: No module named flask_minify
'''

**Comment by app-generator** [comment]
Hello @tnniras 

Just checked the latest version and looks good. Tests were made:

- Docker 
- LIVE Deploy on Render. 

If you're 100% sure that all the installation steps are executed (modules installed, `export FLASK_APP=run.py` ..) try to edit the `run.py` and disable the Flask-Minify usage: 

```python
import os
from   flask_migrate import Migrate
# from   flask_minify  import Minify    <-- LINE IS commented
from   sys import exit

... (truncated content) ..

# Comment the page compression
# if not DEBUG:
#     Minify(app=app, html=True, js=False, cssless=False)

```

In all cases, let us know your progress. 
If the issue persists, feel free to access the support page and get in touch with the team

https://appseed.us/support/

**Comment by tnniras** [comment]
Hello There,

Thank you for your help. 

I have currently disabled  `Flask-Minify` and continued with the hosting. But It seems Now I'm unable to login after user registration. 

"It just refreshes the page. "  Just trying to find out how I can solve this issue now.
