### ISSUE TITLE
SQL Server integration?

### ISSUE THREAD

**Issue by vlasvlasvlas** [app-generator/flask-adminlte#3]
Hi! 
This project is amazing, thanks!

Could this be compatible with ms-sqlserver? what strategy do you suggest?

Thanks!

**Comment by app-generator** [comment]
Hello @vlasvlasvlas, 

The project uses SqlAchemy ORM as DB interface. To use `ms-sqlserver`, please follow this simple set up: 

- make sure you have MsSql up & running in your environment
- Install the [pymssql](https://pypi.org/project/pymssql/) driver
- Update the project configuration to use it - [config.py](https://github.com/app-generator/flask-dashboard-adminlte/blob/master/config.py) 

Let us know the results. 
P.S. Thank you for using our projects.

**Comment by vlasvlasvlas** [comment]
thanks a lot! ill test it and let you know :)

**Comment by vlasvlasvlas** [comment]
Hi, i tested and got an error,

i installed pymssql and this is what i did with config.py

>    
    SQLALCHEMY_DATABASE_URI = '{}://{}:{}@{}:{}/{}'.format(
        config( 'DB_ENGINE'   , default='SQL Server'    ),
        config( 'DB_USERNAME' , default='sa'       ),
        config( 'DB_PASS'     , default='sqlrealpassword'          ),
        config( 'DB_HOST'     , default='realipserver'     ),
        config( 'DB_PORT'     , default=1433            ),
        config( 'DB_NAME'     , default='realdatabasename' )
    )

dunno where i can find the logs

**Comment by vlasvlasvlas** [comment]
UPDATE 4:

I successfuly usde pymssql hardcoding the create engine string.

But now i have the following issue when the create user table is executed:

> sqlalchemy.exc.OperationalError: (pymssql._pymssql.OperationalError) (1919, b"Column 'email' in table 'User' is of a type that is invalid for use as a key column in an index.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")
> [SQL:
> CREATE TABLE [User] (
>         id INTEGER NOT NULL IDENTITY(1,1),
>         username VARCHAR(max) NULL,
>         email VARCHAR(max) NULL,
>         password VARBINARY(max) NULL,
>         PRIMARY KEY (id),
>         UNIQUE (username),
>         UNIQUE (email)
> )
> 
> ]


I think there's an issue inside the create table (here's an sqlserver2019) with the varchar(MAX) and nvarchar(MAX) used in indices.

**Comment by app-generator** [comment]
Hello Vladimiro,

Try to limit the VARCHAR fields to 900:

"username VARCHAR(900) NULL,
email VARCHAR(900) NULL,
"

More information regarding this fix, you can find here:
https://stackoverflow.com/questions/2863993/is-of-a-type-that-is-invalid-for-use-as-a-key-column-in-an-index

Let us know if you have further issues.

AppSeed.us Support

**Comment by vlasvlasvlas** [comment]
Hi! yes! i made that change at models.py,

i got a new one thats at the insert step:
![imagen](https://user-images.githubusercontent.com/4071796/114946667-fe26d800-9e21-11eb-9f87-f4ee5ff9cdc4.png)

for this, i did a manual sql insert and then i could login:
> INSERT INTO [User] (username, email, password) 
> VALUES 
> ('admin',
> 'admin@admin.com', 
> convert(varbinary(max),'1a656bc4d631781429dbc6060546bda5df32bb475fb8fd21e8d86bf339f08372ece4bdefac18f9248edb478f06c5d7ac9ec4337ba09da845ae5d8acbbbd8e890e0d131a040ed0f2144f6fada7a535e6ee52915adbceba2321c7d6ca43560d67b')
> )

But i do need to get the insert done from the code. I think its about the convert( varbinary(max) thing that the code is just inserting string without converting to varbinary(max).

thanks a lot!
